import { useEffect, useState, useSyncExternalStore } from 'react';
import { Link, useParams, useNavigate } from 'react-router';
import { Building2, FileText, Bell, ShieldCheck, Target, Users, Globe, LayoutDashboard, Landmark, Settings, Download, Plus, ArrowUpRight, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { authStore } from '../components/auth-store';
import { useLanguage } from '../components/LanguageContext';
import { getOrgId } from '../lib/api';
import { managementRequest, fileBase64, saveDownload, type Definition, type ManagementState, type ManagementRecord, type ManagementDocument } from '../lib/management-api';
import { PageHeader, SectionHeader, SearchField, StatusBadge } from '../components/product';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { Input } from '../components/ui/input';
import { Textarea } from '../components/ui/textarea';

const modules=[
 ['dashboard','لوحة الإدارة','Overview',LayoutDashboard],['companies','الشركات','Companies',Building2],['basic-info','المعلومات الأساسية','Basic information',Building2],['legal','القانونية والتسجيل','Legal & registration',ShieldCheck],['governance','الحوكمة','Governance',Users],['financial','المالية','Financial',Landmark],['operations','العمليات','Operations',Target],['technology','التكنولوجيا','Technology',Globe],['compliance','الامتثال والمخاطر','Compliance & risks',ShieldCheck],['company-profile','ملف الشركة','Company profile',Building2],['bank-accounts','الحسابات البنكية','Bank accounts',Landmark],['vision-mission','الرؤية والرسالة','Vision & mission',Target],['management','الإدارة والمجلس','Executives & board',Users],['social-media','التواجد الرقمي','Digital presence',Globe],['filings','الإيداعات والتقارير','Filings & reports',FileText],['documents','المستندات','Documents',FileText],['alerts','التنبيهات','Alerts',Bell],['settings','الإعدادات','Settings',Settings],
] as const;
const labels:Record<string,[string,string]>={valid:['ساري','Current'],expiring:['ينتهي قريبًا','Expiring soon'],expired:['منتهي','Expired'],undated:['بدون تاريخ انتهاء','No expiry date'],critical:['أساسي','Essential'],important:['مهم','Important'],optional:['اختياري','Optional'],legal:['قانوني','Legal'],tax:['ضريبي','Tax'],hr:['موارد بشرية','HR'],financial:['مالي','Financial'],operations:['تشغيلي','Operations'],technology:['تقني','Technology'],governance:['حوكمة','Governance'],none:['بدون تكرار','One-time'],monthly:['شهري','Monthly'],quarterly:['ربع سنوي','Quarterly'],annual:['سنوي','Annual'],available:['متاح','Available'],pending:['قيد الانتظار','Pending'],submitted:['تم الإرسال','Submitted'],completed:['مكتمل','Completed'],not_required:['غير مطلوب','Not required'],management:['الإدارة التنفيذية','Management'],board:['مجلس الإدارة','Board'],review:['للمراجعة','Review'],compliant:['مستوفى','Satisfied'],attention:['يحتاج معالجة','Needs attention'],not_applicable:['لا ينطبق','Not applicable'],low:['منخفض','Low'],medium:['متوسط','Medium'],high:['مرتفع','High'],in_progress:['قيد التنفيذ','In progress'],SA:['السعودية','Saudi Arabia'],'US-WY':['وايومنغ','Wyoming'],'US-IRS':['فيدرالي IRS','Federal IRS'],OTHER:['أخرى','Other']};
const routeFor=(kind:string)=>({requirement:'documents',filing:'filings',control:'compliance',task:'operations',goal:'vision-mission',member:'management',digital:'social-media'}[kind]||'dashboard');
const selectClass='h-10 w-full rounded-md border border-input bg-background px-3 text-sm';

export function CompanyManagement(){
 const orgId=useSyncExternalStore(cb=>authStore.subscribe(cb),()=>getOrgId(),()=>null);
 return orgId?<ManagementWorkspace key={orgId} orgId={orgId}/>:<p>اختر منشأة / Select a company</p>;
}
function ManagementWorkspace({orgId}:{orgId:string}){
 const {section='dashboard'}=useParams(),{t}=useLanguage(),navigate=useNavigate();
 const [state,setState]=useState<ManagementState|null>(null),[error,setError]=useState(''),[enabled,setEnabled]=useState<boolean|null>(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[revision,setRevision]=useState(0);
 const [editor,setEditor]=useState<{definition:Definition;record?:ManagementRecord;kind:string;initial?:Record<string,any>;title?:string}|null>(null);
 const [upload,setUpload]=useState<ManagementRecord|null>(null),[preview,setPreview]=useState<{url:string;name:string;mime:string}|null>(null);
 const [jurisdiction,setJurisdiction]=useState('all'),[filter,setFilter]=useState('all'),[archive,setArchive]=useState<ManagementRecord|null>(null),[busy,setBusy]=useState(false);
 const word=(value:string)=>labels[value]?t(...labels[value]):value;
 const refresh=()=>{setRevision(x=>x+1)};
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');managementRequest<{enabled:boolean}>(orgId,'/access',undefined,'GET',controller.signal).then(async access=>{setEnabled(access.enabled);if(access.enabled)setState(await managementRequest<ManagementState>(orgId,'',undefined,'GET',controller.signal))}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[orgId,revision]);
 useEffect(()=>{setEditor(null);setUpload(null);setQuery('');setFilter('all');setArchive(null)},[section]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview.url)},[preview]);
 const showFile=async(doc:ManagementDocument,download=false)=>{try{const d=await managementRequest<{fileBase64:string;mimeType:string;fileName:string}>(orgId,`/documents/${doc.id}/content`);const bytes=Uint8Array.from(atob(d.fileBase64),c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:d.mimeType});if(download)saveDownload(blob,d.fileName);else setPreview({url:URL.createObjectURL(blob),name:d.fileName,mime:d.mimeType})}catch(e:any){toast.error(e.message)}};
 const module=modules.find(x=>x[0]===section);
 if(!module)return <p>{t('القسم غير موجود','Section not found')} <Link to="/app/management">{t('العودة للإدارة','Back to management')}</Link></p>;
 return <div className="space-y-6" dir={t('rtl','ltr')}>
 <PageHeader eyebrow="ENTIX" title={t('إدارة الشركة','Company management')} description={state?.org.name||t('معلومات المنشأة ووثائقها والتزاماتها في مكان واحد','Company information, documents and obligations in one place')} leading={<Building2 className="size-7 text-primary"/>} actions={<Link to="/app"><Button variant="outline">{t('العودة للمحاسبة','Back to accounting')}</Button></Link>}/>
 <label className="flex max-w-md items-center gap-3 text-sm"><span className="shrink-0">{t("انتقل إلى", "Go to")}</span><select className={selectClass} value={section} onChange={e=>navigate(`/app/management/${e.target.value}`)}>{modules.map(([key,ar,en])=><option key={key} value={key}>{t(ar,en)}</option>)}</select></label>
 <nav aria-label={t('أقسام إدارة الشركة','Company management sections')} className="flex gap-2 overflow-x-auto pb-2">{modules.map(([key,ar,en,Icon])=><Link key={key} to={`/app/management/${key}`} aria-current={section===key?'page':undefined} className={`flex shrink-0 items-center gap-2 rounded-lg border px-3 py-2 text-sm ${section===key?'border-primary bg-primary/10 text-primary':'border-border bg-card text-muted-foreground hover:text-foreground'}`}><Icon className="size-4"/>{t(ar,en)}</Link>)}</nav>
 {error&&<div role="alert" className="rounded-lg border border-warning bg-warning/10 p-4">{error}<Button onClick={refresh} variant="outline" className="ms-3">{t('إعادة المحاولة','Retry')}</Button></div>}
 {loading&&!state?<div role="status" className="flex items-center gap-2 p-8"><Loader2 className="size-5 animate-spin"/>{t('تحميل بيانات المنشأة…','Loading company data…')}</div>:enabled===false?<Card><CardContent className="space-y-4 p-6"><h2 className="text-section">{t('إدارة الشركة ضمن الباقة العليا','Company management for the highest tier')}</h2><p>{t('يمكن تفعيلها أيضًا كإضافة مخصصة. لا تُفرض رسوم من هذه الصفحة.','It can also be enabled as a dedicated add-on. This page does not charge you.')}</p><Link to="/app/billing"><Button>{t('عرض اشتراك المنشأة','View company subscription')}</Button></Link></CardContent></Card>:state&&<>
 {preview?<Card><CardContent className="space-y-4 p-6"><SectionHeader title={preview.name} actions={<Button variant="outline" onClick={()=>setPreview(null)}>{t('إغلاق المعاينة','Close preview')}</Button>}/>{preview.mime==='application/pdf'?<iframe title={preview.name} src={preview.url} sandbox="" className="h-[70vh] w-full rounded-lg border"/>:<img alt={preview.name} src={preview.url} className="max-h-[70vh] w-full object-contain"/>}</CardContent></Card>:editor?<RecordEditor key={editor.record?.id||editor.definition.key} {...editor} orgId={orgId} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);refresh()}}/>:upload?<UploadEditor record={upload} orgId={orgId} onClose={()=>setUpload(null)} onSaved={()=>{setUpload(null);refresh()}}/>:<>
 <SectionHeader title={t(module[1],module[2])}/>
 {section==='dashboard'&&<Dashboard state={state}/>}
 {section==='companies'&&<CompanyDirectory orgId={orgId}/>}
 {['bank-accounts','company-profile'].includes(section)&&<Card><CardContent className="space-y-4 p-6"><p>{t('مرتبطة ببيانات المحاسبة الحالية. تعديل البيانات من سجلها الرئيسي يحافظ على تطابقها في كامل المنصة.','Connected to your accounting data. Edit the master record to keep the platform consistent.')}</p><Link to={section==='bank-accounts'?'/app/bank-accounts':'/app/settings?tab=company'}><Button>{t(section==='companies'?'إدارة المنشآت':section==='bank-accounts'?'فتح الحسابات البنكية':'تعديل ملف المنشأة',section==='companies'?'Manage companies':section==='bank-accounts'?'Open bank accounts':'Edit company profile')}<ArrowUpRight className="ms-2 size-4"/></Button></Link>{section==='company-profile'&&<dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(state.org).filter(([k])=>k!=='id').map(([k,v])=><div key={k} className="border-b py-2"><dt className="text-sm text-muted-foreground">{masterLabel(k,t)}</dt><dd className="break-words">{v==null?'—':String(v)}</dd></div>)}</dl>}{section==='companies'&&<p className="text-sm text-muted-foreground">{t('بدّل المنشأة من قائمة المنشآت أعلى القائمة الرئيسية.','Switch companies using the company selector above the main navigation.')}</p>}</CardContent></Card>}
 {state.catalog.areas.filter(a=>a.key===section).map(def=>{const record=state.records.find(r=>r.kind==='profile'&&r.key===def.key);return <Card key={def.key}><CardContent className="space-y-5 p-6"><SectionHeader title={t(def.ar,def.en)} actions={<Button onClick={()=>setEditor({definition:def,kind:'profile',record})}>{t('تعديل المعلومات','Edit information')}</Button>}/><dl className="grid gap-4 sm:grid-cols-2">{def.fields.map(f=><div key={f.key}><dt className="text-sm text-muted-foreground">{t(f.ar,f.en)}</dt><dd className="whitespace-pre-wrap break-words">{record?.data[f.key]!==undefined?word(String(record.data[f.key])):'—'}</dd></div>)}</dl>{section==='basic-info'&&<Link to="/app/settings?tab=company" className="text-primary">{t('الاسم والنشاط والعنوان وبيانات التواصل ← ملف المنشأة','Name, activity, address and contact details → company profile')}</Link>}{section==='financial'&&<Link to="/app/bank-accounts" className="text-primary">{t('الحسابات البنكية','Bank accounts')} · {state.counts.banks}</Link>}{section==='operations'&&<div className="flex gap-5"><Link className="text-primary" to="/app/branches">{t('الفروع','Branches')} · {state.counts.branches}</Link><Link className="text-primary" to="/app/employees">{t('الموظفون','Employees')} · {state.counts.employees}</Link></div>}</CardContent></Card>})}
 {section==='management'&&<Link to="/app/shareholders" className="inline-flex items-center gap-2 text-primary"><Users className="size-4"/>{t('سجل الملاك ونسب الملكية','Owners register & ownership interests')} · {state.counts.owners}</Link>}
 {section==='social-media'&&<p className="text-sm text-muted-foreground">{t('الروابط والإحصاءات مدخلة يدويًا. الربط المباشر يتطلب تفويض المنصة الخارجية.','Links and metrics are maintained manually. Live integration requires authorization from the external platform.')}</p>}
 {['documents','legal','filings','compliance'].includes(section)&&<div className="flex flex-wrap items-center gap-3"><select aria-label={t('الاختصاص','Jurisdiction')} className={`${selectClass} max-w-xs`} value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}><option value="all">{t('كل الاختصاصات','All jurisdictions')}</option>{['SA','US-WY','US-IRS','OTHER'].map(x=><option key={x} value={x}>{word(x)}</option>)}</select><Link className="text-primary" to="/app/ai">{t('مساعد الذكاء الاصطناعي','AI assistant')} ↗</Link></div>}
 {section==='documents'&&<BatchExtraction orgId={orgId} definition={state.catalog.collections.find(x=>x.key==='requirement')!} onSaved={refresh}/>}
 {section==='alerts'&&<Alerts state={state}/>}
 {section==='filings'&&<FilingSummary state={state} jurisdiction={jurisdiction}/>}
 {['documents','filings','legal','compliance','management','social-media','operations','vision-mission'].includes(section)&&<SearchField aria-label={t('بحث في السجلات','Search records')} placeholder={t('ابحث بالاسم أو التفاصيل…','Search names or details…')} value={query} onChange={e=>setQuery(e.target.value)}/>}
 {state.catalog.collections.filter(def=>({documents:['requirement'],legal:['requirement'],filings:['filing'],compliance:['control'],management:['member'],'social-media':['digital'],operations:['task'],'vision-mission':['value','goal']}[section]||[]).includes(def.key)).map(def=>{
 const items=state.records.filter(r=>r.kind===def.key&&(jurisdiction==='all'||!r.data.jurisdiction||r.data.jurisdiction===jurisdiction)&&(filter==='all'||(def.key==='requirement'?state.documents.find(d=>d.recordId===r.id)?.status===filter:r.data.status===filter||r.data.group===filter||r.data.category===filter))&&JSON.stringify([r.title,r.data]).toLowerCase().includes(query.toLowerCase()));
 const templates=def.key==='requirement'?state.catalog.requirementTemplates:def.key==='filing'?state.catalog.filingTemplates:null;
 return <div key={def.key} className="space-y-4"><SectionHeader title={t(def.ar,def.en)} actions={<Button onClick={()=>setEditor({definition:def,kind:def.key})}><Plus className="me-2 size-4"/>{t('إضافة','Add')}</Button>}/>
 <div className="flex flex-wrap gap-2"><Button variant={filter==='all'?'default':'outline'} size="sm" onClick={()=>setFilter('all')}>{t('الكل','All')}</Button>{(def.key==='requirement'?['valid','expiring','expired','undated']:def.fields.find(f=>f.key==='status'||f.key==='group')?.options||[]).map(x=><Button key={x} size="sm" variant={filter===x?'default':'outline'} onClick={()=>setFilter(x)}>{word(x)}</Button>)}</div>
 {templates&&<details className="rounded-lg border bg-card p-4"><summary className="cursor-pointer text-sm text-primary">{t('اختيار قالب متابعة','Choose a tracking template')}</summary><p className="my-3 text-sm text-muted-foreground">{t('اختر ما ينطبق على المنشأة وراجع المتطلبات والمواعيد قبل اعتماده. القالب لا يعني تقديمًا رسميًا.','Choose what applies and verify requirements and dates. A template is not an official submission.')}</p><div className="flex flex-wrap gap-2">{Object.entries(templates).filter(([j])=>jurisdiction==='all'||j===jurisdiction).flatMap(([j,names])=>names.map(name=><Button key={j+name} variant="outline" size="sm" onClick={()=>setEditor({definition:def,kind:def.key,title:name,initial:{jurisdiction:j,...(def.key==='requirement'?{category:'legal',priority:'important',recurrence:'none'}:{status:'available'})}})}>{name} · {word(j)}</Button>))}</div></details>}
 {items.length===0?<Card><CardContent className="p-8 text-center text-muted-foreground">{t('لا توجد سجلات مطابقة. أضف أول سجل للمنشأة.','No matching records. Add your first company record.')}</CardContent></Card>:<div className={`grid gap-4 ${def.key==='requirement'?'md:grid-cols-2 xl:grid-cols-3':'md:grid-cols-2'}`}>{items.map(record=>{const docs=state.documents.filter(d=>d.recordId===record.id),latest=docs[0];return <Card key={record.id}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-semibold text-foreground">{record.title}</h3><StatusBadge tone={latest?.status==='valid'||record.data.status==='completed'?'success':latest?.status==='expired'||latest?.status==='expiring'?'warning':'neutral'}>{word(latest?.status||record.data.status||record.data.group||record.data.category||record.kind)}</StatusBadge></div><dl className="space-y-2 text-sm">{def.fields.filter(f=>record.data[f.key]!==undefined).map(f=><div key={f.key} className="flex flex-wrap justify-between gap-2"><dt className="text-muted-foreground">{t(f.ar,f.en)}</dt><dd className="max-w-full whitespace-pre-wrap break-words">{word(String(record.data[f.key]))}</dd></div>)}</dl>{latest&&<p className="text-sm text-muted-foreground">{t('انتهاء','Expires')}: {latest.expiresAt?.slice(0,10)||'—'} · {t('الإصدار','Revision')} {latest.revision}</p>}
 <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setEditor({definition:def,kind:def.key,record})}>{t('تعديل','Edit')}</Button>{['requirement','filing','control'].includes(def.key)&&<Button size="sm" onClick={()=>setUpload(record)}>{t('رفع مستند','Upload document')}</Button>}<Button size="sm" variant="ghost" onClick={()=>setArchive(record)}>{t('أرشفة','Archive')}</Button></div>
 {['filing','control','requirement'].includes(def.key)&&<RecordAssistant orgId={orgId} record={record}/>}
 {docs.length>0&&<details><summary className="cursor-pointer text-sm text-primary">{t('المستندات والإصدارات','Documents & revisions')} ({docs.length})</summary><ul className="mt-3 space-y-3">{docs.map(doc=><li key={doc.id} className="space-y-1 border-t pt-2"><span className="block break-words text-sm">{doc.fileName} · v{doc.revision}</span><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>showFile(doc)}>{t('معاينة','Preview')}</Button><Button size="sm" variant="ghost" onClick={()=>showFile(doc,true)}><Download className="me-1 size-4"/>{t('تنزيل','Download')}</Button></div></li>)}</ul></details>}
 </CardContent></Card>})}</div>}</div>})}
 {section==='settings'&&<><ManagementAudit orgId={orgId} state={state}/><ArchivedRecords orgId={orgId} onRestored={refresh}/></>}
 {archive&&<Card><CardContent className="space-y-3 p-5"><p>{t('أرشفة السجل مع الاحتفاظ بمستنداته وسجل تعديلاته؟','Archive this record while retaining its documents and audit history?')} {archive.title}</p><div className="flex gap-2"><Button disabled={busy} onClick={async()=>{setBusy(true);try{await managementRequest(orgId,`/records/${archive.id}/archive`,{version:archive.version});setArchive(null);refresh()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>{t('أرشفة السجل','Archive record')}</Button><Button variant="outline" onClick={()=>setArchive(null)}>{t('إلغاء','Cancel')}</Button></div></CardContent></Card>}
 </>}
 </>}
 </div>;
}

function masterLabel(key:string,t:(ar:string,en:string)=>string){const m:Record<string,[string,string]>={name:['اسم المنشأة','Company name'],legalName:['الاسم القانوني','Legal name'],legalType:['الشكل القانوني','Legal form'],country:['الدولة','Country'],state:['الولاية','State'],baseCurrency:['العملة الأساسية','Base currency'],crNumber:['السجل التجاري','Registration number'],vatNumber:['الرقم الضريبي','Tax number'],email:['البريد الإلكتروني','Email'],phone:['الهاتف','Phone'],website:['الموقع','Website'],industry:['النشاط','Activity'],addressLine:['العنوان','Address'],city:['المدينة','City'],region:['المنطقة','Region'],district:['الحي','District'],streetName:['الشارع','Street'],buildingNumber:['رقم المبنى','Building number'],postalCode:['الرمز البريدي','Postal code'],fiscalYearEnd:['شهر نهاية السنة المالية','Fiscal year end month']};return m[key]?t(...m[key]):key}

function RecordEditor({definition,record,kind,initial,title,orgId,onClose,onSaved}:{definition:Definition;record?:ManagementRecord;kind:string;initial?:Record<string,any>;title?:string;orgId:string;onClose:()=>void;onSaved:(record:ManagementRecord)=>void}){
 const {t}=useLanguage(),[name,setName]=useState(record?.title||title||t(definition.ar,definition.en)),[values,setValues]=useState<Record<string,any>>(record?.data||initial||{}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Card><CardContent className="p-6"><form className="space-y-6" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const submitted=Object.fromEntries(definition.fields.flatMap(f=>{const value=String(form.get(f.key)??'').trim();return value===''?[]:[[f.key,f.type==='number'?Number(value):value]]}));setBusy(true);setError('');try{const saved=await managementRequest<ManagementRecord>(orgId,record?`/records/${record.id}`:'/records',{kind,key:kind==='profile'?definition.key:undefined,title:name,data:submitted,version:record?.version},record?'PUT':'POST');toast.success(t('تم الحفظ','Saved'));onSaved(saved)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
 <SectionHeader title={t(definition.ar,definition.en)}/>{kind!=='profile'&&<label className="block space-y-2"><span>{t('الاسم','Name')}</span><Input required maxLength={240} value={name} onChange={e=>setName(e.target.value)}/></label>}
 <div className="grid gap-5 sm:grid-cols-2">{definition.fields.map(f=>{const set=(v:string)=>setValues(prev=>{const next={...prev};if(v==='')delete next[f.key];else next[f.key]=f.type==='number'?Number(v):v;return next});return <label key={f.key} className={`block space-y-2 ${f.type==='textarea'?'sm:col-span-2':''}`}><span className="text-sm">{t(f.ar,f.en)} {f.required&&kind!=='profile'?'*':''}</span>{f.type==='select'?<select name={f.key} className={selectClass} required={kind!=='profile'&&f.required} value={values[f.key]??''} onChange={e=>set(e.target.value)}><option value="">{t('اختر','Choose')}</option>{f.options?.map(x=><option key={x} value={x}>{labels[x]?t(...labels[x]):x}</option>)}</select>:f.type==='textarea'?<Textarea name={f.key} rows={5} maxLength={20000} required={kind!=='profile'&&f.required} value={values[f.key]??''} onChange={e=>set(e.target.value)}/>:<Input name={f.key} type={f.type||'text'} min={f.type==='number'?0:undefined} max={f.max} step={f.type==='number'?'any':undefined} maxLength={500} required={kind!=='profile'&&f.required} value={values[f.key]??''} onChange={e=>set(e.target.value)}/>}</label>})}</div>
 {error&&<p role="alert" className="text-warning">{error}</p>}<div className="flex gap-3"><Button type="submit" disabled={busy}>{busy?t('جارٍ الحفظ…','Saving…'):t('حفظ','Save')}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>{t('إلغاء','Cancel')}</Button></div></form></CardContent></Card>
}

function UploadEditor({record,orgId,onClose,onSaved,initialFile,initialDates}:{record:ManagementRecord;orgId:string;onClose:()=>void;onSaved:()=>void;initialFile?:File;initialDates?:{issuedAt?:string;expiresAt?:string}}){
 const {t}=useLanguage(),[file,setFile]=useState<File|null>(initialFile??null),[issued,setIssued]=useState(initialDates?.issuedAt||''),[expires,setExpires]=useState(initialDates?.expiresAt||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Card><CardContent className="p-6"><form className="space-y-5" onSubmit={async e=>{e.preventDefault();const uploadForm=new FormData(e.currentTarget);if(!file)return;setBusy(true);setError('');try{if(file.size>10*1024*1024)throw new Error(t('الحد الأقصى 10 ميجابايت','Maximum 10 MB'));await managementRequest(orgId,'/documents',{recordId:record.id,version:record.version,fileName:file.name,mimeType:file.type,fileBase64:await fileBase64(file),issuedAt:String(uploadForm.get('issuedAt')||'')||undefined,expiresAt:String(uploadForm.get('expiresAt')||'')||undefined});onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
 <SectionHeader title={`${t('رفع إصدار مستند','Upload document revision')} · ${record.title}`} description={t('PDF، PNG، JPEG · 10 ميجابايت. يحتفظ النظام بالإصدارات السابقة.','PDF, PNG, JPEG · 10 MB. Previous revisions are retained.')}/><label className="block space-y-2"><span>{t('المستند','Document')} {file?.name}</span><Input type="file" accept="application/pdf,image/png,image/jpeg" required={!file} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><div className="grid gap-4 sm:grid-cols-2"><label>{t('تاريخ الإصدار','Issued on')}<Input name="issuedAt" type="date" value={issued} onChange={e=>setIssued(e.target.value)}/></label><label>{t('تاريخ الانتهاء','Expires on')}<Input name="expiresAt" type="date" min={issued||undefined} value={expires} onChange={e=>setExpires(e.target.value)}/></label></div>{error&&<p role="alert">{error}</p>}<div className="flex gap-3"><Button type="submit" disabled={busy}>{busy?t('جارٍ الرفع…','Uploading…'):t('حفظ المستند','Save document')}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>{t('إلغاء','Cancel')}</Button></div></form></CardContent></Card>
}

function latestDocuments(state:ManagementState){return state.documents.filter((d,i,all)=>all.findIndex(x=>x.recordId===d.recordId)===i)}
function Dashboard({state}:{state:ManagementState}){
 const {t}=useLanguage(),docs=latestDocuments(state),requirements=state.records.filter(r=>r.kind==='requirement'&&r.data.priority!=='optional');
 const areas=state.catalog.areas.slice(0,7).map(area=>{const data=state.records.find(r=>r.kind==='profile'&&r.key===area.key)?.data||{};let values=area.fields.filter(f=>f.required).map(f=>data[f.key]!==undefined&&data[f.key]!=='');if(area.key==='basic-info')values.push(!!state.org.name,!!state.org.industry,!!state.org.email);if(area.key==='legal')values.push(...requirements.filter(r=>r.data.category==='legal'||r.data.category==='tax').map(r=>docs.some(d=>d.recordId===r.id&&d.status!=='expired'&&d.status!=='undated')));if(area.key==='financial')values.push(state.counts.banks>0,!!state.org.fiscalYearEnd);return {...area,total:values.length,done:values.filter(Boolean).length,percent:values.length?Math.round(values.filter(Boolean).length/values.length*100):0}});
 const total=areas.reduce((n,a)=>n+a.total,0),done=areas.reduce((n,a)=>n+a.done,0),percent=total?Math.round(done/total*100):0;
 const missing=requirements.filter(r=>!docs.some(d=>d.recordId===r.id&&['valid','expiring'].includes(d.status)));
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-6 rounded-xl bg-foreground p-6 text-background"><div><p className="text-sm opacity-80">{t('اكتمال معلومات المنشأة','Company information completeness')}</p><p className="mt-2 text-4xl font-semibold">{percent}%</p><p className="mt-2 text-xs opacity-80">{t('مؤشر بيانات، وليس شهادة امتثال رسمي','Data readiness indicator, not an official compliance certificate')}</p></div><div className="flex flex-wrap gap-8">{[['valid','سارية','Current'],['expiring','تنتهي قريبًا','Expiring'],['expired','منتهية','Expired']].map(([status,ar,en])=><div key={status}><p className="text-2xl font-semibold">{docs.filter(d=>d.status===status).length}</p><p className="mt-1 text-sm opacity-80">{t(ar,en)}</p></div>)}</div></div>
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{modules.filter(m=>['company-profile','bank-accounts','vision-mission','management','documents','filings'].includes(m[0])).map(([key,ar,en,Icon])=><Link key={key} to={`/app/management/${key}`} className="flex items-center gap-2 rounded-lg border bg-card p-4 text-sm hover:border-primary"><Icon className="size-5 text-primary"/>{t(ar,en)}</Link>)}</div>
 <div className="grid gap-5 lg:grid-cols-2"><Card><CardContent className="space-y-5 p-6"><SectionHeader title={t('تقدم المعلومات','Information progress')}/>{areas.map(a=><Link key={a.key} to={`/app/management/${a.key}`} className="block space-y-2"><div className="flex justify-between text-sm"><span>{t(a.ar,a.en)}</span><span>{a.total?`${a.percent}%`:t('لم يحدد','Not configured')}</span></div><div role="progressbar" aria-label={t(a.ar,a.en)} aria-valuemin={0} aria-valuemax={100} aria-valuenow={a.percent} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${a.percent}%`}}/></div></Link>)}</CardContent></Card><Card><CardContent className="space-y-4 p-6"><SectionHeader title={t('المعلومات والمستندات المطلوبة','Missing information & documents')}/>{areas.filter(a=>a.done<a.total).map(a=><Link key={a.key} to={`/app/management/${a.key}`} className="flex justify-between rounded-lg bg-muted p-3 text-sm"><span>{t(a.ar,a.en)}</span><span>{a.total-a.done} {t('حقول','fields')}</span></Link>)}{missing.slice(0,5).map(r=><Link key={r.id} to="/app/management/documents" className="block rounded-lg bg-warning/10 p-3 text-sm">{r.title}</Link>)}{!requirements.length&&<p className="text-sm text-muted-foreground">{t('أضف المتطلبات المناسبة للمنشأة ليبدأ احتساب جاهزية المستندات.','Add applicable requirements to start tracking document readiness.')}</p>}<Link to="/app/management/documents"><Button className="mt-3 w-full">{t('إدارة المستندات','Manage documents')}</Button></Link></CardContent></Card></div><Alerts state={state} compact/></div>
}
function Alerts({state,compact=false}:{state:ManagementState;compact?:boolean}){const {t}=useLanguage(),days=Number(state.records.find(r=>r.kind==='profile'&&r.key==='settings')?.data.reminderDays??30),deadline=new Date(Date.parse(state.serverDate)+days*86400000).toISOString().slice(0,10);const documents=latestDocuments(state).filter(d=>['expired','expiring'].includes(d.status));const tasks=state.records.filter(r=>r.data.dueDate&&r.data.dueDate<=deadline&&!['completed','not_required','not_applicable'].includes(r.data.status));return <Card><CardContent className="space-y-4 p-6"><SectionHeader title={t('المواعيد والتنبيهات','Deadlines & alerts')}/>{!documents.length&&!tasks.length?<p className="text-sm text-muted-foreground">{t('لا توجد مواعيد مسجلة تستدعي تنبيهًا.','No recorded deadlines require attention.')}</p>:<ul className="space-y-3">{documents.slice(0,compact?5:undefined).map(d=><li key={d.id}><Link to="/app/management/documents" className="flex flex-wrap justify-between gap-2 rounded-lg bg-warning/10 p-3 text-sm"><span>{state.records.find(r=>r.id===d.recordId)?.title} · {d.fileName}</span><time>{d.expiresAt?.slice(0,10)}</time></Link></li>)}{tasks.slice(0,compact?5:undefined).map(r=><li key={r.id}><Link to={`/app/management/${routeFor(r.kind)}`} className="flex justify-between rounded-lg bg-muted p-3 text-sm"><span>{r.title}</span><time>{r.data.dueDate}</time></Link></li>)}</ul>}</CardContent></Card>}
function ManagementAudit({orgId,state}:{orgId:string;state:ManagementState}){const {t}=useLanguage(),[items,setItems]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();managementRequest<{items:any[]}>(orgId,'/audit',undefined,'GET',c.signal).then(r=>setItems(r.items)).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[orgId]);return <Card><CardContent className="space-y-4 p-6"><SectionHeader title={t('سجل التعديلات وتصدير البيانات','Audit history & data export')} actions={<Button variant="outline" onClick={()=>saveDownload(new Blob([JSON.stringify({format:'entix-management-v1',exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),'company-management.json')}>{t('تصدير البيانات','Export data')}</Button>}/><p className="text-sm text-muted-foreground">{t('التصدير يشمل البيانات وفهرس المستندات؛ يمكن تنزيل الملفات من قسم المستندات.','Export includes data and document metadata; download the files from Documents.')}</p>{error&&<p role="alert">{error}</p>}<ul className="space-y-2">{items.map(i=><li key={i.id} className="flex flex-wrap justify-between gap-2 border-b py-2 text-sm"><span>{t(i.action.includes('upload')?'رفع مستند':i.action.includes('archive')?'أرشفة سجل':i.action.includes('create')?'إضافة سجل':'تعديل سجل',i.action)} · {state.records.find(r=>r.id===i.entityId)?.title||t('سجل مؤرشف','Archived record')}</span><time>{new Date(i.createdAt).toLocaleString()}</time></li>)}</ul></CardContent></Card>}
function BatchExtraction({orgId,definition,onSaved}:{orgId:string;definition:Definition;onSaved:()=>void}){
 const {t}=useLanguage(),[busy,setBusy]=useState(false),[results,setResults]=useState<any[]>([]),[review,setReview]=useState<number|null>(null),[saved,setSaved]=useState<ManagementRecord|null>(null);
 return <Card><CardContent className="space-y-4 p-6"><SectionHeader title={t('قراءة المستندات بالذكاء الاصطناعي','AI document extraction')} description={t('حتى 10 ملفات. راجع النتائج قبل حفظها. يُستهلك رصيد الذكاء الاصطناعي عند القراءة.','Up to 10 files. Review results before saving. Extraction uses your AI allowance.')}/><label className="block space-y-2"><span className="text-sm">{t('اختيار المستندات للاستخراج','Choose documents to extract')}</span><Input type="file" multiple disabled={busy} accept="application/pdf,image/png,image/jpeg" onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;if(files.length>10||files.some(f=>f.size>10*1024*1024)){toast.error(t('حتى 10 ملفات، كل ملف 10 ميجابايت أو أقل','Up to 10 files, each 10 MB or less'));return}setBusy(true);setResults([]);setReview(null);setSaved(null);for(const file of files){try{const result=await managementRequest<any>(orgId,'/extract',{fileName:file.name,mimeType:file.type,fileBase64:await fileBase64(file)});setResults(prev=>[...prev,{fileName:file.name,file,...result}])}catch(e:any){setResults(prev=>[...prev,{fileName:file.name,error:e.message}])}}setBusy(false)}}/></label>{busy&&<p role="status">{t('جارٍ قراءة المستندات…','Reading documents…')}</p>}
 {review!==null&&!saved&&<RecordEditor key={review} definition={definition} kind="requirement" title={results[review].extracted.title} initial={{category:results[review].extracted.category,jurisdiction:results[review].extracted.jurisdiction,priority:'important',recurrence:'none',notes:results[review].extracted.summary}} orgId={orgId} onClose={()=>setReview(null)} onSaved={record=>setSaved(record)}/>}
 {saved&&review!==null&&<UploadEditor record={saved} orgId={orgId} initialFile={results[review].file} initialDates={results[review].extracted} onClose={()=>{setSaved(null);setReview(null);onSaved()}} onSaved={()=>{setResults(prev=>prev.map((r,i)=>i===review?{...r,stored:true}:r));setSaved(null);setReview(null);onSaved()}}/>}
 {results.map((r,i)=><div key={i} className="space-y-2 rounded-lg border p-3"><h3 className="font-medium">{r.fileName}</h3>{r.error?<p role="alert">{r.error}</p>:<><p className="text-sm">{r.extracted.summary}</p><p className="text-sm text-muted-foreground">{t('الإصدار','Issued')}: {r.extracted.issuedAt||'—'} · {t('الانتهاء','Expires')}: {r.extracted.expiresAt||'—'}</p>{r.extracted.uncertainties?.map((text:string,j:number)=><p key={j} className="text-sm text-warning">{text}</p>)}<Button variant="outline" disabled={busy||r.stored||review!==null} onClick={()=>setReview(i)}>{r.stored?t('تم الحفظ','Saved'):t('مراجعة وحفظ','Review & save')}</Button></>}</div>)}
 </CardContent></Card>}

function ArchivedRecords({orgId,onRestored}:{orgId:string;onRestored:()=>void}){const {t}=useLanguage(),[items,setItems]=useState<ManagementRecord[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();managementRequest<{items:ManagementRecord[]}>(orgId,'/archived',undefined,'GET',c.signal).then(r=>setItems(r.items)).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[orgId]);return <Card><CardContent className="space-y-4 p-6"><SectionHeader title={t('السجلات المؤرشفة','Archived records')}/>{error&&<p role="alert">{error}</p>}{!items.length&&<p className="text-sm text-muted-foreground">{t('لا توجد سجلات مؤرشفة','No archived records')}</p>}{items.map(r=><div key={r.id} className="flex items-center justify-between gap-3 border-b py-2"><span>{r.title}</span><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await managementRequest(orgId,`/records/${r.id}/restore`,{version:r.version});setItems(prev=>prev.filter(x=>x.id!==r.id));onRestored()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{t('استعادة','Restore')}</Button></div>)}</CardContent></Card>}

function CompanyDirectory({orgId}:{orgId:string}){const {t}=useLanguage(),[items,setItems]=useState<any[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();managementRequest<{items:any[]}>(orgId,'/companies',undefined,'GET',controller.signal).then(r=>setItems(r.items)).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[orgId]);return <div className="space-y-4"><SectionHeader title={t('منشآتك','Your companies')} actions={<><Button variant="outline" onClick={()=>window.dispatchEvent(new Event('entix:open-switcher'))}>{t('تبديل المنشأة','Switch company')}</Button><Link to="/app/settings?tab=company"><Button>{t('إدارة المنشآت','Manage companies')}</Button></Link></>}/><SearchField aria-label={t('بحث الشركات','Search companies')} value={query} onChange={e=>setQuery(e.target.value)}/><div className="flex gap-2">{[['all','الكل','All'],['current','مستندات سارية','Current documents'],['expiring','تنبيه قريب','Upcoming alerts'],['expired','تحتاج معالجة','Needs attention']].map(([key,ar,en])=><Button key={key} size="sm" variant={filter===key?'default':'outline'} onClick={()=>setFilter(key)}>{t(ar,en)}</Button>)}</div>{error&&<p role="alert">{error}</p>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.filter(o=>o.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='current'&&o.documents>0&&!o.expired&&!o.expiring||filter==='expiring'&&o.expiring>0||filter==='expired'&&o.expired>0)).map(o=><Card key={o.id}><CardContent className="space-y-3 p-5"><h3 className="font-semibold">{o.name}</h3><p className="text-sm text-muted-foreground">{o.country} · {o.legalType||'—'}</p><div className="flex flex-wrap gap-2"><StatusBadge>{o.documents} {t('مستندات','documents')}</StatusBadge><StatusBadge tone={o.expired||o.expiring?'warning':'neutral'}>{o.expired+o.expiring} {t('تنبيهات','alerts')}</StatusBadge></div>{o.id===orgId?<Link className="text-primary" to="/app/management/dashboard">{t('فتح لوحة المنشأة','Open company overview')}</Link>:<Button variant="outline" onClick={()=>window.dispatchEvent(new Event('entix:open-switcher'))}>{t('اختيار المنشأة من القائمة','Choose company from selector')}</Button>}</CardContent></Card>)}</div></div>}

function FilingSummary({state,jurisdiction}:{state:ManagementState;jurisdiction:string}){const {t}=useLanguage(),rows=state.records.filter(r=>r.kind==='filing'&&(jurisdiction==='all'||r.data.jurisdiction===jurisdiction));return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['completed','مكتمل','Completed',rows.filter(r=>r.data.status==='completed').length],['pending','قيد المتابعة','In progress',rows.filter(r=>['pending','submitted'].includes(r.data.status)).length],['late','متأخر','Overdue',rows.filter(r=>r.data.dueDate&&r.data.dueDate<state.serverDate&&!['completed','not_required'].includes(r.data.status)).length],['available','متاح','Available',rows.filter(r=>r.data.status==='available').length]].map(([key,ar,en,count])=><Card key={String(key)}><CardContent className="space-y-2 p-5"><p className="text-2xl font-semibold">{count}</p><p className="text-sm text-muted-foreground">{t(String(ar),String(en))}</p></CardContent></Card>)}</div>}
function RecordAssistant({orgId,record}:{orgId:string;record:ManagementRecord}){const {t}=useLanguage(),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm text-primary">{t('الحصول على مساعدة','Get assistance')}</summary><form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await managementRequest<{answer:string}>(orgId,'/assist',{recordId:record.id,question});setAnswer(r.answer)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label className="block space-y-2 text-sm"><span>{t('سؤالك عن هذا السجل','Question about this record')}</span><Textarea required maxLength={4000} value={question} onChange={e=>setQuestion(e.target.value)}/></label><p className="text-xs text-muted-foreground">{t('تستهلك المساعدة رصيد الذكاء الاصطناعي. الإجابة للمراجعة ولا تمثل قبولًا أو إيداعًا رسميًا.','Assistance uses your AI allowance. Review the answer; it does not constitute official acceptance or filing.')}</p><Button type="submit" size="sm" disabled={busy}>{busy?t('جارٍ التحضير…','Preparing…'):t('تحضير الإجابة','Prepare answer')}</Button>{error&&<p role="alert">{error}</p>}{answer&&<p className="whitespace-pre-wrap text-sm leading-7">{answer}</p>}</form></details>}
