# syntax=docker/dockerfile:1.6
# Multi-stage build for Entix Books frontend (Vite + React)

# ── Build stage ──────────────────────────────────────────────────────────────
FROM node:22.22.0-bookworm-slim AS build
# Force rebuild - security + nginx fix 2026-08-03
WORKDIR /app
ARG CACHE_BUST=1
RUN echo "Cache bust: $CACHE_BUST"

# Puppeteer runs only in the builder. The final nginx image receives static,
# prerendered HTML and does not contain Node or Chromium.
RUN apt-get update \
  && apt-get install -y --no-install-recommends chromium ca-certificates fonts-liberation \
  && rm -rf /var/lib/apt/lists/*
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Install deps · cache layer for npm
COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .
# Vite bakes VITE_* vars at build time — Coolify passes build-time env as
# Docker build args, so declare + export it before the vite build runs.
ARG VITE_TURNSTILE_SITEKEY=""
ENV VITE_TURNSTILE_SITEKEY=$VITE_TURNSTILE_SITEKEY
RUN npm run build

# ── Serve stage ──────────────────────────────────────────────────────────────
FROM nginx:1.27-alpine AS serve
# Copy Vite build output (default dist/)
COPY --from=build /app/dist /usr/share/nginx/html
# `Link: rel=preload` for the hashed stylesheet (generated by scripts/prerender.mjs
# each build) → Cloudflare Early Hints (103) so the render-blocking CSS is fetched
# before the HTML body finishes streaming from the origin.
COPY --from=build /app/nginx-early-hints.conf /etc/nginx/snippets/early-hints.conf
# Edge-cache purge on every container start (needs CF_ZONE_ID + CF_PURGE_TOKEN at runtime).
COPY docker/99-purge-cloudflare.sh /docker-entrypoint.d/99-purge-cloudflare.sh
RUN chmod +x /docker-entrypoint.d/99-purge-cloudflare.sh

# Custom nginx config · SPA fallback + immutable asset cache
RUN cat > /etc/nginx/conf.d/default.conf <<'NGINX'
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  absolute_redirect off;

  # Early Hints preload for the current build's stylesheet (server scope → only
  # reaches locations without their own add_header, i.e. the HTML documents).
  include /etc/nginx/snippets/early-hints.conf;

  # Extensionless prerendered routes (especially /login) stay in their original
  # location after try_files: the .html rule below does not apply to them.
  # Never retain a document pointing to an obsolete application bundle.
  add_header Cache-Control "no-cache, no-store, must-revalidate" always;

  # Security headers (SEC-01 · 2026-08-27). These lived in the Cloudflare
  # worker (worker.js) before DNS moved to Coolify; the nginx origin sent none.
  # `always` keeps them on 3xx/4xx. CSP is intentionally NOT set here yet —
  # the app calls Plaid/GLEIF/Nominatim/OpenRouter and a blind policy could
  # break a paying customer; tracked as tech debt TD-SEC-CSP.
  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), interest-cohort=()" always;

  # Canonical host and HTTPS are fixed rather than derived from an untrusted Host
  # header or the container's internal HTTP scheme behind Cloudflare/Coolify.
  if ($host = "www.entix.io") {
    return 308 https://entix.io$request_uri;
  }
  if ($http_x_forwarded_proto = "http") {
    return 308 https://entix.io$request_uri;
  }

  # Neutral chooser and the exact localized manifest artifacts.
  location = / { try_files /index.html =404; }
  location = /sa/ar { try_files /sa/ar/index.html =404; }
  location = /sa/en { try_files /sa/en/index.html =404; }
  location = /us/ar { try_files /us/ar/index.html =404; }
  location = /us/en { try_files /us/en/index.html =404; }

  # Existing dashboard bookmarks resolve to the authenticated application entry.
  location = /dashboard { return 308 /app$is_args$args; }
  location = /dashboard/ { return 308 /app$is_args$args; }

  # Canonical localized URLs have no trailing slash. Relative redirects retain
  # the browser's external HTTPS origin even though Nginx receives proxy HTTP.
  location = /sa/ar/ { return 308 /sa/ar$is_args$args; }
  location = /sa/en/ { return 308 /sa/en$is_args$args; }
  location = /us/ar/ { return 308 /us/ar$is_args$args; }
  location = /us/en/ { return 308 /us/en$is_args$args; }

  # Any other market/locale path is outside the constrained manifest.
  location ~ ^/(?:sa|us)/(?:ar|en)(?:/|$) { return 404; }

  # Canonicalize established public documents to no trailing slash. With
  # absolute_redirect disabled these remain same-origin HTTPS at the edge.
  location ~ ^/(features|pricing|referrals|about|contact|blog|docs|help|videos|glossary|case-studies|changelog|roadmap|partners|careers|team|integration|privacy|terms|refund|sla|login|register|forgot-password|reset-password|connect)/$ {
    return 308 /$1$is_args$args;
  }
  location ~ ^/(solutions/(?:small-business|accountants|enterprises|restaurants|ecommerce|contracting|freelancers|agencies)|support/ios)/$ {
    return 308 /$1$is_args$args;
  }

  # Established public routes are real prerendered documents. Exact matching and
  # $uri/index.html prevent neutral-root shell substitution if an artifact is absent.
  location ~ ^/(?:features|pricing|referrals|about|contact|blog|docs|help|videos|glossary|case-studies|changelog|roadmap|partners|careers|team|integration|privacy|terms|refund|sla|login|register|forgot-password|reset-password|connect)$ {
    try_files $uri/index.html =404;
  }
  location ~ ^/solutions/(?:small-business|accountants|enterprises|restaurants|ecommerce|contracting|freelancers|agencies)$ {
    try_files $uri/index.html =404;
  }
  location = /support/ios { try_files $uri/index.html =404; }

  # Controlled application surfaces remain client-rendered. invite/verify-email
  # are emailed auth-flow landings — they must serve the shell (they 404'd on
  # the honest-404 rule, breaking every invite + verification link 2026-08-21).
  # /admin is the standalone platform console shell (Z2.1) — direct load 404'd
  # 2026-08-26 because the prefix was missing here.
  # /q = public quote-accept links (SPEC-04) · /b = public branded boards (SPEC-06)
  location ~ ^/(?:app|admin|portal|print|invite|verify-email|welcome|buy|claim|q|b)(?:/|$) { try_files $uri /app-shell.html; }

  # Unknown extensionless paths are honest 404s rather than SPA fake-200s.
  location / { try_files $uri =404; }

  # Sitemap must answer application/xml and revalidate — GSC "Couldn't fetch"
  # incidents trace back to stale/guess-typed responses. robots stays text/plain.
  location = /sitemap.xml {
    types { application/xml xml; }
    default_type application/xml;
    add_header Cache-Control "no-cache, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    try_files $uri =404;
  }
  location = /robots.txt {
    default_type text/plain;
    add_header Cache-Control "no-cache, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    try_files $uri =404;
  }

  # Serve .well-known as static files with correct content type
  # (Microsoft identity verification requires application/json)
  location /.well-known/ {
    try_files $uri =404;
    default_type application/json;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  }

  # The API-hosted OAuth consent page uses the same public brand fonts.
  location ^~ /fonts/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Access-Control-Allow-Origin "https://api.entix.io" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  }

  # Self-healing for edge-cached HTML (PERF-03 · 2026-10-10): public documents are
  # cached at Cloudflare for up to 1h; after a deploy a cached document can still
  # reference a hashed bundle this container no longer has. Instead of a 404 (blank
  # page) the missing *module* answers with a tiny script that reloads the page once
  # with a cache-busting query → fresh HTML from the origin. Hashed assets that exist
  # are untouched (regex location below). Only /assets/*.js — never other paths.
  location ~ ^/assets/[\w.-]+\.js$ {
    try_files $uri @stale-bundle;
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  }
  location @stale-bundle {
    default_type application/javascript;
    add_header Cache-Control "no-store" always;
    add_header X-Entix-Stale-Bundle "1" always;
    return 200 "(function(){try{var q=location.search;if(q.indexOf('__r=')===-1){location.replace(location.pathname+(q?q+'&':'?')+'__r='+Date.now()+location.hash)}}catch(e){}})();";
  }

  # Cache hashed assets aggressively
  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  }

  # Service worker must always revalidate · a stale SW would pin old bundles
  # (exact match beats the regex block above)
  location = /sw.js {
    expires -1;
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Pragma "no-cache";
  }

  # Every HTML document, including prerendered nested route files, must revalidate.
  location ~* \.html$ {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Pragma "no-cache";
  }
}
NGINX

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
