import { test, expect } from '@playwright/test';
import { prepareVisualApp } from './fixtures/visual-app';
for(const language of ['en','ar'] as const)test(`bank review offers journal/account/transfer and retains failed input (${language})`,async({page})=>{
 await prepareVisualApp(page,language);await page.setViewportSize({width:1440,height:1100});
 const bank={id:'bank-test',name:'Synthetic Wise',country:'US',currency:'USD',balance:'0',isActive:true};
 await page.route('**/api/bank-accounts',r=>r.fulfill({json:{items:[bank],total:1}}));
 await page.route('**/api/bank-accounts/bank-test/activity',r=>r.fulfill({json:{items:[]}}));
 await page.route('**/api/vouchers?*',r=>r.fulfill({json:{items:[]}}));
 const rows=[{id:'unknown',date:'2016-08-02',description:'Unrecognized bank movement',amount:-.2,currency:'USD',status:'UNMATCHED',reference:null},{id:'known',date:'2016-08-02',description:'Existing posted transfer',amount:100,currency:'USD',status:'UNMATCHED',reference:null},{id:'transfer',date:'2016-08-02',description:'New internal transfer',amount:-100,currency:'USD',status:'UNMATCHED',reference:null}];
 await page.route('**/api/bank-import/transactions?*',r=>r.fulfill({json:{transactions:rows,counts:{UNMATCHED:rows.length}}}));
 await page.route('**/api/bank-import/transactions/*/suggestions',r=>r.fulfill({json:{baseCurrency:'USD',accounts:[{id:'fees',name:'Bank fees',nameAr:'رسوم بنكية',code:'6100',type:'EXPENSE'}],banks:[{id:'other',name:'Synthetic Mercury',currency:'USD'}],options:r.request().url().includes('/known/')?[{id:'journal',label:'JV-2016-00001',kind:'journal',outstanding:100,date:'2016-08-02',score:95}]:[],match:r.request().url().includes('/known/')?{type:'journal',id:'journal',confidence:.95}:{type:'unknown',confidence:0}}}));
 const calls:any[]=[];let fail=true;
 await page.route('**/api/bank-import/transactions/*/match',async r=>{const id=r.request().url().split('/').at(-2);const body=r.request().postDataJSON();calls.push({id,...body});if(id==='unknown'&&fail){fail=false;return r.fulfill({status:503,json:{error:'temporary_failure'}});}const index=rows.findIndex(x=>x.id===id);if(index>=0)rows.splice(index,1);return r.fulfill({json:{ok:true,status:'MATCHED'}});});
 await page.goto('/app/bank-accounts/bank-test');
 const unknown=page.getByTestId('bank-review-unknown'),known=page.getByTestId('bank-review-known'),transfer=page.getByTestId('bank-review-transfer');
 const confirm=language==='ar'?'تأكيد':'Confirm';
 await expect(unknown.getByRole('button',{name:confirm,exact:true})).toBeDisabled();
 await expect(known.getByText('JV-2016-00001',{exact:false})).toBeVisible();
 await expect(known.getByText(language==='ar'?'مطابقة فقط · لن يُنشأ قيد أو مبلغ إضافي.':'Match only · no additional entry or amount.',{exact:true})).toBeVisible();
 await unknown.getByLabel(language==='ar'?'طريقة المعالجة':'Treatment').selectOption('account');
 await unknown.getByRole('button',{name:language==='ar'?'اختر…':'Choose…',exact:true}).click();await page.getByRole('button',{name:/Bank fees|رسوم بنكية/}).click();
 await page.screenshot({path:`/tmp/entix-bank-choices-${language}.png`,fullPage:true});
 await unknown.getByRole('button',{name:confirm,exact:true}).click();await expect(unknown.getByRole('alert')).toBeVisible();
 await expect(unknown.getByRole('button',{name:language==='ar'?'رسوم بنكية':'Bank fees',exact:true})).toBeVisible();
 await unknown.getByRole('button',{name:confirm,exact:true}).click();await expect(unknown).toHaveCount(0);expect(calls.slice(0,2).every(c=>c.action==='categorize'&&c.accountId==='fees'&&c.learn===true)).toBe(true);
 await known.getByRole('button',{name:confirm,exact:true}).click();await expect(known).toHaveCount(0);expect(calls[2]).toMatchObject({action:'link_journal',targetId:'journal'});
 await transfer.getByLabel(language==='ar'?'طريقة المعالجة':'Treatment').selectOption('transfer');await transfer.getByRole('button',{name:language==='ar'?'اختر…':'Choose…',exact:true}).click();await page.getByRole('button',{name:'Synthetic Mercury · USD',exact:true}).click();
 await page.screenshot({path:`/tmp/entix-bank-review-${language}.png`,fullPage:true});
 await transfer.getByRole('button',{name:confirm,exact:true}).click();await expect(transfer).toHaveCount(0);expect(calls[3]).toMatchObject({action:'transfer',targetId:'other',learn:true});
});
