import { useEffect, useState } from 'react';
import { RefreshCw, CheckCircle2, Clock, MessageSquare, Star, Users } from 'lucide-react';
import { supportDesk } from '../lib/support-desk-api';
import { SUPPORT_CATEGORY, SUPPORT_CHANNEL, type SupportMetrics, type SupportCounter } from '../lib/support-presentation';
import { useLanguage } from './LanguageContext';
import { Button } from './ui/button';

export function SupportPerformance({version=0}:{version?:number}) {
 const {t}=useLanguage();
 const [days,setDays]=useState('30'),[who,setWho]=useState('all'),[data,setData]=useState<SupportMetrics|null>(null),[error,setError]=useState(false),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{let alive=true;setLoading(true);setError(false);supportDesk.metrics(days).then(d=>{if(alive && d.overall && Array.isArray(d.agents))setData(d);else if(alive)setError(true)}).catch(()=>{if(alive)setError(true)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false};},[days,version,refresh]);
 const duration=(ms:number|null)=>ms==null?'—':ms<60000?t('أقل من دقيقة','< 1 min'):ms<3600000?`${Math.round(ms/60000)} ${t('دقيقة','min')}`:ms<86400000?`${(ms/3600000).toFixed(1)} ${t('ساعة','h')}`:`${(ms/86400000).toFixed(1)} ${t('يوم','days')}`;
 const average=(c:SupportCounter)=>c.averageRating==null?'—':`${c.averageRating.toFixed(1)} / 5`;
 const current=who==='mine'?data?.currentAgent:who;
 const selected=who==='all'?data?.overall:data?.agents.find(a=>a.email===current);
 const cards=selected?[
  [t('تحتاج رد الفريق','Needs a team reply'),selected.needsReply,t('تذاكر نشطة','Active tickets'),MessageSquare,'bg-amber-50 text-amber-900'],
  [t('تم الحل والإغلاق','Resolved & closed'),who==='all'?selected.resolved+selected.closed:selected.resolved,t('تم توثيق الحل','Recorded resolutions'),CheckCircle2,'bg-emerald-50 text-emerald-800'],
  [t('أول رد بشري','First human response'),duration(selected.averageResponseMs),`${selected.responseSamples} ${t('تذكرة لها رد','replied tickets')}`,Clock,'bg-blue-50 text-blue-800'],
  [t('متوسط وقت الحل','Average resolution'),duration(selected.averageResolutionMs),`${selected.resolutionSamples} ${t('تذكرة بوقت موثق','timed resolutions')}`,Clock,'bg-violet-50 text-violet-800'],
  [t('رضا العملاء','Customer satisfaction'),average(selected),`${selected.ratings} ${t('تقييم','ratings')}`,Star,'bg-amber-50 text-amber-900'],
  [t('أولوية عالية وعاجلة','High & urgent'),selected.urgent,t('تذاكر نشطة','Active tickets'),Users,'bg-orange-50 text-orange-900'],
 ]:[];
 return <section className="min-w-0 space-y-4" aria-label={t('مؤشرات الدعم الفني','Support performance')}>
  <div className="flex flex-wrap items-end justify-between gap-3">
   <div><h2 className="text-lg font-semibold">{t('أداء فريق الدعم','Support team performance')}</h2><p className="text-xs text-muted-foreground">{t('التذاكر المنشأة خلال الفترة المختارة، ضمن الشركات المتاحة لك.','Tickets created in the selected period, within your company access.')}</p></div>
   <div className="flex flex-wrap items-center gap-2 text-sm">
    <label>{t('الفترة','Period')} <select className="rounded-lg border border-border bg-card p-2" value={days} onChange={e=>setDays(e.target.value)}><option value="7">{t('7 أيام','7 days')}</option><option value="30">{t('30 يومًا','30 days')}</option><option value="90">{t('90 يومًا','90 days')}</option><option value="all">{t('كل الفترات','All time')}</option></select></label>
    <label>{t('عرض الأداء','Performance view')} <select className="max-w-full rounded-lg border border-border bg-card p-2" value={who} onChange={e=>setWho(e.target.value)}><option value="all">{t('الفريق كله','Whole team')}</option><option value="mine">{t('أدائي','My performance')}</option>{data?.agents.map(a=><option key={a.email} value={a.email}>{a.email}</option>)}</select></label>
    <Button variant="outline" size="sm" aria-label={t('تحديث المؤشرات','Refresh metrics')} onClick={()=>setRefresh(v=>v+1)} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></Button>
   </div>
  </div>
  {error?<p role="alert" className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-900">{t('تعذر تحميل المؤشرات. أعد المحاولة؛ لا تمثل القيم السابقة الفترة الجديدة.','Metrics could not load. Retry; previous values do not represent the new period.')}</p>:loading?<p role="status" className="p-4 text-sm text-muted-foreground">{t('جارٍ تحديث المؤشرات…','Updating metrics…')}</p>:<>
  {!selected && <p className="rounded-lg border border-border p-4 text-sm">{t('لا توجد تذاكر أو ردود مسندة لهذا الوكيل في الفترة.','No tickets or replies attributed to this agent in this period.')}</p>}
  <div className="grid grid-cols-2 gap-3 2xl:grid-cols-6 lg:grid-cols-3">{cards.map(([title,value,caption,Icon,tone]:any)=><div key={title} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-2"><span className="text-sm text-muted-foreground">{title}</span><span className={`rounded-lg p-2 ${tone}`}><Icon className="h-4 w-4"/></span></div><p className="mt-3 text-xl sm:text-2xl font-semibold tabular-nums" dir="auto">{value}</p><p className="mt-1 text-xs text-muted-foreground">{caption}</p></div>)}</div>
  {selected && <div className="flex flex-wrap gap-3 text-sm"><span>{who==='all'?t('إجمالي التذاكر','Total tickets'):t('المسندة حاليًا','Currently assigned')}: <b>{selected.total}</b></span><span>{t('مفتوحة','Open')}: <b>{selected.open}</b></span><span>{t('بانتظار العميل','Waiting for customer')}: <b>{selected.pending}</b></span><span className="text-emerald-800">{t('تقييم مرتفع (4–5)','Positive (4–5)')}: <b>{selected.positive}</b></span><span>{t('محايد (3)','Neutral (3)')}: <b>{selected.neutral}</b></span><span className="text-orange-900">{t('تقييم منخفض (1–2)','Negative (1–2)')}: <b>{selected.negative}</b></span></div>}
  {data && <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
   <div className="min-w-0 rounded-xl border border-border bg-card p-4"><h3 className="mb-3 font-semibold">{t('أداء الوكلاء — سجل داخلي','Agent performance — internal record')}</h3><div className="overflow-x-auto"><table className="w-full text-start text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground">{[t('الوكيل','Agent'),t('تم الحل','Resolved'),t('ردود بشرية','Human replies'),t('أول رد','First response'),t('وقت الحل','Resolution time'),t('التقييم','Rating'),t('مرتفع / منخفض','Positive / negative')].map(h=><th key={h} className="whitespace-nowrap px-2 py-3 text-start">{h}</th>)}</tr></thead><tbody>{data.agents.map(a=><tr key={a.email} className="border-b border-border/60"><td className="max-w-60 break-all p-2"><button className="text-primary underline" onClick={()=>setWho(a.email)}>{a.email}</button>{a.email===data.currentAgent&&<small className="ms-1">{t('(أنت)','(You)')}</small>}</td><td className="p-2">{a.resolved}</td><td className="p-2">{a.replies}</td><td className="whitespace-nowrap p-2">{duration(a.averageResponseMs)}</td><td className="whitespace-nowrap p-2">{duration(a.averageResolutionMs)}</td><td className="whitespace-nowrap p-2"><bdi>{average(a)}</bdi> <small>({a.ratings})</small></td><td className="p-2"><bdi>{a.positive} / {a.negative}</bdi></td></tr>)}</tbody></table></div>{!data.agents.length&&<p className="py-4 text-sm text-muted-foreground">{t('لم يسجل نشاط بشري بعد.','No human activity recorded yet.')}</p>}</div>
   <div className="space-y-4">{[[t('مصادر التواصل','Contact channels'),who==='all'?data.channels:selected?.channels||{},SUPPORT_CHANNEL],[t('أنواع الطلبات','Request categories'),who==='all'?data.categories:selected?.categories||{},SUPPORT_CATEGORY]].map(([title,counts,labels]:any)=><div key={title} className="rounded-xl border border-border bg-card p-4"><h3 className="mb-3 font-semibold">{title}</h3>{Object.entries(counts).sort((a:any,b:any)=>b[1]-a[1]).map(([key,count]:any)=><div key={key} className="mb-3"><div className="mb-1 flex justify-between gap-2 text-sm"><span>{labels[key]?t(labels[key][0],labels[key][1]):key}</span><b>{count}</b></div><div className="h-1.5 rounded bg-muted"><div className="h-full rounded bg-primary" style={{width:`${Math.max(...Object.values(counts as Record<string,number>),1)?count/Math.max(...Object.values(counts as Record<string,number>),1)*100:0}%`}}/></div></div>)}</div>)}</div>
  </div>}
  </>}
  <details className="text-xs text-muted-foreground"><summary className="cursor-pointer">{t('كيف تُحسب المؤشرات؟','How are metrics calculated?')}</summary><p className="mt-2 leading-relaxed">{t('الأوقات بالساعات الفعلية منذ إنشاء التذكرة. أول رد بشري يُحسب بعد أول رسالة للعميل، ويستبعد ردود الذكاء والملاحظات الداخلية. رد واتساب يحتسب بعد قبول المزود، وليس إثبات التسليم. الحل يُنسب لمن أغلق التذكرة فعليًا، لا لمن أُسندت إليه لاحقًا. التقييمات من بوابة العميل بعد الحل؛ غياب التقييم يظهر بشرطة. المحادثات المحاسبية الآلية أسفل الصفحة ليست تذاكر دعم.','Times use elapsed wall-clock time. First human response follows the first customer message, excluding AI and internal notes. WhatsApp responses require provider acceptance, which is not proof of delivery. Resolutions belong to the closing operator, not a later assignee. Ratings come from the customer portal after resolution; missing ratings show a dash. Accounting assistant conversations below are not support tickets.')}</p>{!!data?.unattributedResolutions&&<p className="mt-1">{data.unattributedResolutions} {t('حلول قديمة أو مغلقة بواسطة العميل دون نسبة مؤكدة لوكيل.','historical or customer-closed resolutions without a verified agent.')}</p>}</details>
 </section>;
}
